name: Deploy Prod Stack

on:
  push:
    branches:
      - prod # Triggers on pushes to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: CDK Deploy Prod Stack
        run: cdk deploy prodGENIEGenAIChatBotStack --require-approval never
